# Generated by Django 5.0.6 on 2024-07-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=34)),
                ('email', models.CharField(max_length=34)),
                ('mob', models.CharField(max_length=34)),
                ('adhar', models.CharField(max_length=34)),
                ('pan', models.CharField(max_length=34)),
                ('accno', models.CharField(max_length=34)),
                ('ifsc', models.CharField(max_length=34)),
                ('gender', models.CharField(max_length=34)),
                ('dob', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
