# Generated by Django 5.0.6 on 2024-07-09 03:40

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='accno',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^\\d{9,18}$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='adhar',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[0-9]{4}[ ]?[0-9]{4}[ ]?[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9].+[@]{1}[a-zA-Z].+[.]{1}com|in|gov|co$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='mob',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^([+]\\d{2}[ ])?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=34, validators=[app1.models.check]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='pan',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[PCAFHT]{1}[A-Z]{1}[0-9]{4}[A-Z]{1}$')]),
        ),
    ]
